#pragma once
/*
* LinearClassifier.hpp
* Created on: 23/9/2024
* Author : Moin Shaikh
*/

#ifndef FEATUREDETECTION_LINEAR_LINEARCPP_LINEARCLASSIFIER_HPP_
#define FEATUREDETECTION_LINEAR_LINEARCPP_LINEARCLASSIFIER_HPP_




#endif //FEATUREDETECTION_LINEAR_LINEARCPP_LINEARCLASSIFIER_HPP_